baseURL = 'http://example.org/'
languageCode = 'sr-SP'
defaultContentLanguage = "sr"
title = 'Хуго сајт'
theme = 'hugo-universal-theme'
[params]
    enableGoogleMaps = false
    disabled_logo = false
    logo = "img/logo.svg"
    logo_small = "img/logo.svg"
    formspree_action = "https://formspree.io/f/myyakjdy"
    contact_form_ajax = false
    style = "default"
  #контакт
    address = """<p class="text-uppercase"><strong>АД ПЕКАРА</strong>
        <br>Светосавска 59, 
        <br>
        <strong>23300 Кикинда, Србија</strong>
      </p>
      """ 
[params.topbar]
    enable = true
    text = "<p>Контактирајте нас на 0230/425-758 или email@gmail.com.</p>"

[params.clients]
    enable = true
    [params.usluga] 
    enable = true
    col = 3
[params.features]
        enable = true
        cols = 3
 [params.testimonials]
        enable = true
        title = "Pozovi nas"
       # subtitle = "Радили смо са много клијената и увек волимо да чујемо да из сарадње изађу срећни и задовољни. Погледајте шта су наши клијенти рекли о нама."
[[params.menu]]
    parent     = "menu.allpages"
    post       = 1

[[menu.main]]
    name       = "Usluge"
    identifier = "menu.usluge"
    url        = "/index.html/#usluga"
    weight     = 2

[[menu.main]]
    identifier = "contact"
    name       = "Контакт"
    url        = "/contact/"
    weight     = 4

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://pionir.org"
    pre = "<i class='fas fa-2x fa-facebook'></i>"
[params.widgets]

    tags = true

 