baseURL = 'https://piileencee.github.io/Frigo-Termo-Max/'
languageCode = 'sr-SP'
defaultContentLanguage = "sr"

theme = 'hugo-universal-theme'
[params]
    enableGoogleMaps = false
    disabled_logo = false
    logo = "img/logo.svg"
    logo_small = "img/logo.svg"
    formspree_action = "https://formspree.io/f/myyakjdy"
    contact_form_ajax = false
    style = "default"
  #контакт
    address = """<p class="text-uppercase"><strong>MARKO KRSTIČEVIĆ</strong>
        <br>SVetosavska 59, 
        <br>
        <strong>23300 Kikinda, Srbija</strong>
      </p>
      """ 
      contact_url ="https://piileencee.github.io/Frigo-Termo-Max/contact/"
[params.topbar]
    enable = true
    text = "<p>Kontaktirajte nas na 0230/425-758 или email@gmail.com.</p>"

[params.clients]
    enable = true
    [params.usluga] 
    enable = true
    col = 3
[params.features]
        enable = true
        cols = 3
 [params.testimonials]
        enable = true
        title = "Pozovi nas"
       
[[params.menu]]
    parent     = "menu.allpages"
    post       = 1

[[menu.main]]
    name       = "Usluge"
    identifier = "menu.usluge"
    url        = "https://piileencee.github.io/Frigo-Termo-Max/#usluga"
    weight     = 2

[[menu.main]]
    identifier = "contact"
    name       = "Kontakt"
    url        = "/contact/"
    weight     = 4

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/"
    pre = "<i class='fas fa-2x fa-facebook'></i>"
[params.widgets]

    tags = true

 