baseURL = 'http://example.org/'
languageCode = 'sr-SP'
defaultContentLanguage = "sr"
title = 'Хуго сајт'
theme = 'hugo-universal-theme'
[params]
     enableGoogleMaps = false
    disabled_logo = false
    logo_text = "Universal"
    logo = "img/logo.png"
    formspree_action = "https://formspree.io/f/myyakjdy"
    contact_form_ajax = false
    style = "default"
  #контакт
    address = """<p class="text-uppercase"><strong>АД ПЕКАРА</strong>
        <br>Светосавска 59, 
        <br>
        <strong>23300 Кикинда, Србија</strong>
      </p>
      """ 
[params.topbar]
    enable = true
    text = "<p>Контактирајте нас на 0230/425-758 или email@gmail.com.</p>"

[params.clients]
    enable = true
[params.features]
        enable = true
        cols = 3
 [params.testimonials]
        enable = true
        title = "Позови нас"
       # subtitle = "Радили смо са много клијената и увек волимо да чујемо да из сарадње изађу срећни и задовољни. Погледајте шта су наши клијенти рекли о нама."
[[params.menu]]
    parent     = "menu.allpages"
    post       = 1

[[menu.main]]
    name       = "Услуге"
    identifier = "menu.usluge"
    url        = "/usluge/"
    weight     = 2

[[menu.main]]
    name       = "Услуга 1"
    url        = "/usluge/usluga1"
    weight     = 1
    parent     = "menu.usluge"

[[menu.main]]
    name       = "Услуга 2"
    url        = "/usluge/usluga2"
    weight     = 2
    parent     = "menu.usluge"
[[menu.main]]
    name = "Услуга 3"
    url = "/usluge/usluga3"
    weight = 3
    parent = "menu.usluge"
 [[menu.main]]
    name = "Услуга 4"
    url = "/usluge/usluga4"
    weight = 4
    parent = "menu.usluge"
[[menu.main]]
    name = "Услуга 5"
    url = "/usluge/usluga5"
    weight = 5
    parent = "menu.usluge"
[[menu.main]]
    name       = "ЧПП"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 3

[[menu.main]]
    identifier = "contact"
    name       = "Контакт"
    url        = "/contact/"
    weight     = 4

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://pionir.org"
    pre = "<i class='fas fa-snowflake'></i>"
[params.widgets]
    categories = true
    tags = true

 